owner: zarvhq
repo: status-page
user-agent: ZarvBot

sites:
  - name: Zarv Website
    url: https://www.zarv.com
  - name: CDN
    url: https://cdn.zarv.com
  - name: Authentication
    url: https://auth.zarv.com

status-website:
  cname: status.zarv.com
  logoUrl: https://cdn.zarv.com/status-page/zarv-logo-square.png
  name: Zarv
  introTitle: Realtime Platform Monitoring
  introMessage: For more information, check out our [**Twitter page**](https://twitter.com/zarvhq) or [***open an issue***](https://github.com/$OWNER/$REPO/issues/new/choose) to our support team.
  apiBaseUrl: https://api.github.com
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  navbar:
    - title: "Home"
      href: /
    - title: Docs
      href: https://docs.zarv.com
    - title: Issues
      href: https://github.com/$OWNER/$REPO/issues
  commitMessages:
    commitAuthorName: "J.A.R.V.I.S"
    commitAuthorEmail: "jarvis@zarv.com"
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 1 * * *"
    uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
