owner: zarvhq
repo: status-page
user-agent: costajoao

sites:
  - name: Zarv Website
    url: https://www.zarv.com
    expectedStatusCodes:
      - 200
      - 201
  - name: CDN
    url: https://cdn.zarv.com
    expectedStatusCodes:
      - 200
      - 201
  - name: Auth
    url: https://auth.zarv.com
    icon: https://cdn.zarv.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
  - name: Whatsapp API
    url: $WHATSAPP_URL
  - name: Email API
    check: "tcp-ping"
    url: $EMAIL_URL
    port: $EMAIL_PORT


status-website:
  cname: status.zarv.com
  logoUrl: https://cdn.zarv.com/status-page/zarv-logo-square.png
  favicon: https://cdn.zarv.com/favicon.ico
  name: Zarv
  theme: light
  introTitle: Realtime Platform Monitoring
  introMessage: For more information, check out our [**Twitter page**](https://twitter.com/zarvhq) or [***open an issue***](https://github.com/zarvhq/status-page/issues/new/choose) to our support team.
  apiBaseUrl: https://api.github.com
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: "Home"
      href: /
    - title: Docs
      href: https://docs.zarv.com
    - title: Issues
      href: https://github.com/$OWNER/$REPO/issues
  commitMessages:
    commitAuthorName: "J.A.R.V.I.S"
    commitAuthorEmail: "jarvis@zarv.com"
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 1 * * *"
    uptime: "*/5 * * * *"